### ISSUE TITLE
com.valvesoftware.Steam.Utility.gamescope is end-of-life

### ISSUE THREAD

**Issue by FOSSProponent9436** [flathub/com.usebottles.bottles#452]
When I use flatpak update in the CLI I get this message:
```
Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
Info: applications using this extension:
   com.usebottles.bottles
```

I'll add that I'm not sure if this is coming up just because I have it installed and the bottles flatpak CAN use the deprecated one or because the bottles flatpak hasn't been updated to make use of the migrated version at all.

**Comment by orowith2os** [comment]
IIRC this should've also been solved with https://github.com/flathub/com.usebottles.bottles/pull/450; @koplo199 is it not working properly? The CI is all green.

**Comment by koplo199** [comment]
@orowith2os Currently the CI is only checking if there's any new Bottles release, and there isn't any. When there will be one, be it `51.7` or `52`, it should create the necessary pull request. I say should because it needs the right permissions to do so, this is why I opened https://github.com/flathub/com.usebottles.bottles/issues/451.

**Comment by koplo199** [comment]
@orowith2os I opened #453, so we don't have to wait for a new release.
